### PR TITLE
services-merge

### PR DESCRIPTION
**Pull request by follen99**

### CODE REVIEW

**Review by RaffaeleIzzo01 — CHANGES_REQUESTED** [review]
we need a dto.user package

**Review by Mattia-Marino — CHANGES_REQUESTED** [review]
Some folders for DTOs are missing

**Review by Mattia-Marino — APPROVED** [review]

**Comment by follen99** [comment]
Everithing ok? ❤️ 😘

**Review by RaffaeleIzzo01 — APPROVED** [review]
everything ok

**Pull request merged**
